name: Build Custom Bazzite ISO
on:
  schedule:
    - cron: "00 17 * * *" # Rebuilds automatically every day
  push:
    branches:
      - main
  workflow_dispatch: # Allows you to trigger it manually

jobs:
  bluebuild:
    name: Build Custom Image and ISO
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build ISO via BlueBuild
        uses: blue-build/github-action@v1
        with:
          recipe: 'Containerfile'
          no_sign_image: true
          generate_iso: true
          iso_name: 'nucbox-g5-custom-bazzite-latest.iso'
