name: Build Custom Bazzite ISO
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  bluebuild:
    name: Build Custom Image and ISO
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build ISO via BlueBuild
        uses: blue-build/github-action@v1
        with:
          recipe: 'Containerfile'
          generate_iso: true
          iso_name: 'nucbox-g5-custom-bazzite-latest.iso'
          # This line completely stops the signing sub-tool from running
          is_pro_installer: false
